// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {updater} from '../models';
import {config} from '../models';
import {accounts} from '../models';

export function ActivateAccount(arg1:number):Promise<void>;

export function AddBreakpointRule(arg1:string,arg2:string):Promise<proxy.BreakpointRule>;

export function CheckCertTrust():Promise<boolean>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function CreateAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteBreakpointRule(arg1:string):Promise<void>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallCert():Promise<void>;

export function ListAccounts():Promise<Array<accounts.AccountDTO>>;

export function OpenProjectInIDE():Promise<void>;

export function RegisterTypes():Promise<proxy.PendingRequest|proxy.WebSocketFrame>;

export function ResumeRequest(arg1:string,arg2:proxy.ModifiedRequest):Promise<boolean>;

export function SyncGetUser():Promise<string>;

export function SyncPull(arg1:string):Promise<string>;

export function SyncPush(arg1:string):Promise<void>;

export function SyncSignIn(arg1:string,arg2:string):Promise<void>;

export function SyncSignUp(arg1:string,arg2:string):Promise<void>;

export function UpdateAppConfig(arg1:config.AppConfig):Promise<void>;

export function UploadSession(arg1:proxy.ProxyRequestEvent):Promise<string>;
