// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {middleware} from '../models';
import {updater} from '../models';
import {migration} from '../models';
import {config} from '../models';
import {main} from '../models';
import {accounts} from '../models';
import {types} from '../models';

export function ActivateAccount(arg1:number):Promise<void>;

export function AddBreakpointRule(arg1:string,arg2:string):Promise<proxy.BreakpointRule>;

export function AddMapLocalRule(arg1:middleware.MapLocalRule):Promise<void>;

export function CheckCertTrust():Promise<boolean>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function CheckLegacyData():Promise<migration.LegacyStatus>;

export function CloudGetStatus():Promise<Record<string, any>>;

export function CloudLogin(arg1:string,arg2:string):Promise<void>;

export function CloudLogout():Promise<void>;

export function CloudSignUp(arg1:string,arg2:string):Promise<void>;

export function CloudSync():Promise<void>;

export function CreateAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteBreakpointRule(arg1:string):Promise<void>;

export function DeleteMapLocalRule(arg1:string):Promise<void>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetBreakpointRules():Promise<Array<proxy.BreakpointRule>>;

export function GetMapLocalRules():Promise<Array<middleware.MapLocalRule>>;

export function GetScript():Promise<main.ScriptState>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallCert():Promise<void>;

export function ListAccounts():Promise<Array<accounts.AccountDTO>>;

export function OpenProjectInIDE():Promise<void>;

export function PerformLegacyImport():Promise<number>;

export function RegisterTypes():Promise<proxy.PendingRequest>;

export function ResumeRequest(arg1:string,arg2:proxy.ModifiedRequest):Promise<boolean>;

export function SaveWindowSize(arg1:number,arg2:number):Promise<void>;

export function UpdateAppConfig(arg1:config.AppConfig):Promise<void>;

export function UpdateScript(arg1:string,arg2:boolean):Promise<void>;

export function UploadSession(arg1:types.ProxyRequestEvent):Promise<string>;
