// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAccount(arg1) {
  return window['go']['main']['App']['ActivateAccount'](arg1);
}

export function AddBreakpointRule(arg1, arg2) {
  return window['go']['main']['App']['AddBreakpointRule'](arg1, arg2);
}

export function AddMapLocalRule(arg1) {
  return window['go']['main']['App']['AddMapLocalRule'](arg1);
}

export function CheckCertTrust() {
  return window['go']['main']['App']['CheckCertTrust']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckLegacyData() {
  return window['go']['main']['App']['CheckLegacyData']();
}

export function CloudGetStatus() {
  return window['go']['main']['App']['CloudGetStatus']();
}

export function CloudLogin(arg1, arg2) {
  return window['go']['main']['App']['CloudLogin'](arg1, arg2);
}

export function CloudLogout() {
  return window['go']['main']['App']['CloudLogout']();
}

export function CloudSignUp(arg1, arg2) {
  return window['go']['main']['App']['CloudSignUp'](arg1, arg2);
}

export function CloudSync() {
  return window['go']['main']['App']['CloudSync']();
}

export function CreateAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3, arg4);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteBreakpointRule(arg1) {
  return window['go']['main']['App']['DeleteBreakpointRule'](arg1);
}

export function DeleteMapLocalRule(arg1) {
  return window['go']['main']['App']['DeleteMapLocalRule'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetBreakpointRules() {
  return window['go']['main']['App']['GetBreakpointRules']();
}

export function GetMapLocalRules() {
  return window['go']['main']['App']['GetMapLocalRules']();
}

export function GetScript() {
  return window['go']['main']['App']['GetScript']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function OpenProjectInIDE() {
  return window['go']['main']['App']['OpenProjectInIDE']();
}

export function PerformLegacyImport() {
  return window['go']['main']['App']['PerformLegacyImport']();
}

export function RegisterTypes() {
  return window['go']['main']['App']['RegisterTypes']();
}

export function ResumeRequest(arg1, arg2) {
  return window['go']['main']['App']['ResumeRequest'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowSize'](arg1, arg2);
}

export function UpdateAppConfig(arg1) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1);
}

export function UpdateScript(arg1, arg2) {
  return window['go']['main']['App']['UpdateScript'](arg1, arg2);
}

export function UploadSession(arg1) {
  return window['go']['main']['App']['UploadSession'](arg1);
}

export function ScanIDEAccounts() {
  return window['go']['main']['App']['ScanIDEAccounts']();
}

export function ImportDiscoveredAccount(arg1) {
  return window['go']['main']['App']['ImportDiscoveredAccount'](arg1);
}
