// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAccount(arg1) {
  return window['go']['main']['App']['ActivateAccount'](arg1);
}

export function CheckCertTrust() {
  return window['go']['main']['App']['CheckCertTrust']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3, arg4);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function UpdateAppConfig(arg1) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1);
}

export function AddBreakpointRule(arg1, arg2) {
  return window['go']['main']['App']['AddBreakpointRule'](arg1, arg2);
}

export function DeleteBreakpointRule(arg1) {
  return window['go']['main']['App']['DeleteBreakpointRule'](arg1);
}

export function ResumeRequest(arg1, arg2) {
  return window['go']['main']['App']['ResumeRequest'](arg1, arg2);
}
