// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { config } from '../models';
import { updater } from '../models';

export function GetAppConfig(): Promise<config.AppConfig>;

export function GetAppVersion(): Promise<string>;

export function Greet(arg1: string): Promise<string>;

export function UpdateAppConfig(arg1: config.AppConfig): Promise<void>;

export function CheckForUpdates(): Promise<updater.UpdateInfo>;
